# Generated by Django 4.0.1 on 2022-05-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_dpt', models.CharField(max_length=20)),
                ('ac_sem', models.CharField(max_length=20)),
                ('ac_subject', models.CharField(max_length=20)),
                ('ac_authentication', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'authentication_fac',
            },
        ),
    ]
