# Generated by Django 4.0.1 on 2022-05-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_admin_email'),
        ('faculty', '0002_faculty_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_authentication',
            name='faculty_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admins.faculty'),
            preserve_default=False,
        ),
    ]
