# Generated by Django 4.0.1 on 2022-05-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_admin_email'),
        ('faculty', '0003_faculty_authentication_faculty_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculty_authentication',
            new_name='FacultyAuthentication',
        ),
    ]
