# Generated by Django 4.0.1 on 2022-05-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=30)),
                ('dob', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
    ]
