# Generated by Django 4.0.1 on 2022-05-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='dob',
            field=models.CharField(max_length=20),
        ),
    ]
